added secrets

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,6 +10,8 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
+    env :
+      DATABASE_URL: ${{ secrets.DATABASE_URL }}
     steps:
       - name: Checkout into repository
         uses: actions/checkout@v4
@@ -17,6 +19,14 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 22
+      - name: Check Database DATABASE_URL
+        run: |
+          if [-n "$DATABASE_URL" ];then
+            echo "DATABASE_URL loaded success"
+          else
+            echo "DATABASE_URL missing"
+            exit 1
+          fi
       - name: Install Dependencies
         run: npm install
 
